# Cloud Run service configuration
# Can be used with: gcloud run services replace cloudrun.yaml

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: video-game-rag-api
  labels:
    app: video-game-rag
    environment: production
spec:
  template:
    metadata:
      annotations:
        # Autoscaling
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        # CPU throttling (always allocate CPU)
        run.googleapis.com/cpu-throttling: 'false'
        # Startup probe
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 20
      timeoutSeconds: 300
      serviceAccountName: video-game-rag-sa@PROJECT_ID.iam.gserviceaccount.com
      
      containers:
      - name: api
        image: gcr.io/PROJECT_ID/video-game-rag-api:latest
        
        ports:
        - name: http1
          containerPort: 8000
        
        env:
        # Application config
        - name: PORT
          value: '8000'
        - name: LOG_LEVEL
          value: 'INFO'
        - name: API_WORKERS
          value: '1'
        
        # Feature flags
        - name: USE_VERTEX_AI
          value: 'true'
        - name: ENABLE_TRACING
          value: 'true'
        
        # GCP config
        - name: GOOGLE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: google-project-id
              key: latest
        - name: GOOGLE_LOCATION
          value: 'us-central1'
        
        # Pinecone config
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: pinecone-api-key
              key: latest
        - name: PINECONE_INDEX_NAME
          value: 'video-games'
        
        # Phoenix tracing (optional)
        - name: PHOENIX_ENDPOINT
          value: 'https://phoenix-PROJECT_ID.run.app'
        
        resources:
          limits:
            cpu: '2000m'
            memory: '4Gi'
          requests:
            cpu: '1000m'
            memory: '2Gi'
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12

  traffic:
  - percent: 100
    latestRevision: true

